name: Backend Tests

on:
  # Déclenche les tests sur chaque push vers la branche 'main'
  push:
    branches:
      - main
  # Déclenche les tests lors de l'ouverture, mise à jour, ou réouverture d'une pull request
  pull_request:
    types: [opened, synchronize, reopened]  # Ne pas tester lors de la fermeture d'une PR, mais lors de son ouverture/synchronisation

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.0'

    - name: Install dependencies
      run: |
        cd star-wars-backend
        npm install

    - name: Run tests
      run: |
        cd star-wars-backend
        npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test-backend  # Cette étape dépend de la réussite du job 'test-backend'
    steps:
      - name: Trigger webhook for deployment
        run: |
          if [ $? -eq 0 ]; then
            echo "Tests réussis, déclenchement du webhook de déploiement..."
            curl -X POST https://star-wars-encyclopedia-api.com/webhook
          else
            echo "Les tests ont échoué, le déploiement ne sera pas effectué."
            exit 1
